### ISSUE TITLE
Could not find the pga460.h

### ISSUE THREAD

**Issue by yuhshow** [DawnGuardian/PGA460-ESP32_Library#1]
### Description

I have downloaded the using the sketch manger to import the code.  Then I create an arduino scketch and copy the getdistanece.cpp to it. While compiling the code, I got following error message..
D:\OneDrive\PGA460\ESP32_PGA460\AutoThreshold.cpp:1:10: fatal error: PGA460.h: No such file or directory
 #include "PGA460.h"
          ^~~~~~~~~~
compilation terminated.
exit status 1
Please advise where to get the PGA460.h.

### Steps To Reproduce Problem

Please give detailed instructions needed for anyone to attempt to reproduce the problem.

### Hardware & Software

DOIT DEVkit with ESP-WRROM-32 module 
Shields / modules: PGA460PSM
IDE and version: Arduino 1.8.19
Operating system & version  Windows 10
Any other software or hardware? No

### Arduino Sketch

```cpp
// Change the code below by your sketch (please try to give the smallest code which demonstrates the problem)
#include <Arduino.h>

// libraries: give links/details so anyone can compile your code for the same result

void setup() {
}

void loop() {
}
```

### Errors or Incorrect Output

If you see any errors or incorrect output, please show it here.  Please use copy & paste to give an exact copy of the message.  Details matter, so please show (not merely describe) the actual message or error exactly as it appears.

**Comment by DawnGuardian** [comment]
The include directive in that file was not properly implemented, a fix has been deployed to correct it.
